import {writable} from "svelte/store";

export const coursesAndThierLinks = {
    'ECON_201_UGRD': 'https://chat.whatsapp.com/DNQVq7VCNoMBUwCIh9FKEL',
    'ECON_203_UGRD': 'https://chat.whatsapp.com/BTeESFcPY3bEPsvCBfOfb5',
    'PHYS_284_UGRD': 'https://chat.whatsapp.com/C2kieoBaiDnDyAYwZYksoe',
    'MATH_203_UGRD': 'https://chat.whatsapp.com/Gq0p3StsyCS73dHn11JpnL',
    'MATH_204_UGRD': 'https://chat.whatsapp.com/FBfCysPHZbY5dJmOQwewv0',
    'MATH_205_UGRD': 'https://chat.whatsapp.com/DvEgcgrldg3EogDQEHpDVz',
    'MATH_206_UGRD': 'https://chat.whatsapp.com/JFGzvMfqKKJ0GDj4nwoxNe',
    'MATH_251_UGRD': 'https://chat.whatsapp.com/KBbmtKKEwFT874SJEdv6G9',
    'MIAE_221_UGRD': 'https://chat.whatsapp.com/L46MJxdkY703VDJjsLy1X3',
    'MIAE_215_UGRD': 'https://chat.whatsapp.com/KhaLLC9hJiU3Uwt9hhVLaU',
    'MIAE_313_UGRD': 'https://chat.whatsapp.com/JalQQM6mD7iI0WWdczRnom',
    'ENGR_201_UGRD': 'https://chat.whatsapp.com/JiVCujhZI1BKuHvwXYdjSw',
    'ENGR_202_UGRD': 'https://chat.whatsapp.com/B8NjDDNrayQDd3OfUJeOMY',
    'ENGR_371_UGRD': 'https://chat.whatsapp.com/HpcmeUHCewZ57yEUVUeMFO',
    'ENGR_213_UGRD': 'https://chat.whatsapp.com/KZuv6LK3Ta086D1x3J3kBx',
    'ENGR_233_UGRD': 'https://chat.whatsapp.com/DWYNfEigIzTDe1MXxVy60Y',
    'ENGR_311_UGRD': 'https://chat.whatsapp.com/HnQ4GcFb4OU9ilbsn64uwG',
    'ENGR_301_UGRD': 'https://chat.whatsapp.com/GPJdavdPv9xAvraFDCBarz',
    'ENGR_251_UGRD': 'https://chat.whatsapp.com/BdFwJDDgKc7HZuPdw8x6SN',
    'ENGR_242_UGRD': 'https://chat.whatsapp.com/JZUBoCxTDVV7SXLfRytYs4',
    'ENGR_392_UGRD': 'https://chat.whatsapp.com/K1LQQy6bD0GLL8htBQWRT6',
    'ENGR_244_UGRD': 'https://chat.whatsapp.com/EpVpB9odWin0hmKDeVloTx',
    'ENGR_361_UGRD': 'https://chat.whatsapp.com/DcKL3cBg7266uvltgIUsgt',
    'ENGR_243_UGRD': 'https://chat.whatsapp.com/HS6AkJfblWm0wm016MvLlA',
    'ENGR_391_UGRD': 'https://chat.whatsapp.com/BDFzFLaOnKk2f9zG5eOpKf',
    'CHEM_205_UGRD': 'https://chat.whatsapp.com/Bb88taMoywqCmIimaURoMh',
    'COMP_248_UGRD': 'https://chat.whatsapp.com/Ea5dUiZEEIh7EacJmdc3Q8',
    'COMP_249_UGRD': 'https://chat.whatsapp.com/IjFOVEmgOovEqxgE3byGZO',
    'COMP_352_UGRD': 'https://chat.whatsapp.com/GVvLRDDa0asDf0ynLdGXt2',
    'COMP_348_UGRD': 'https://chat.whatsapp.com/GidxnqxtaYg4MVFVmuDy16',
    'COMP_233_UGRD': 'https://chat.whatsapp.com/Dk8hPCwDS65CNvIlVR2RET',
    'COMP_335_UGRD': 'https://chat.whatsapp.com/Jyi35yjfF8aL3JbhdwJZbC',
    'COMP_228_UGRD': 'https://chat.whatsapp.com/JSuRCLTEAjaEtG8odr7flv',
    'COMP_232_UGRD': 'https://chat.whatsapp.com/Hdite158tu8JwIPdCun1Nm',
    'COMP_361_UGRD': 'https://chat.whatsapp.com/FgtwDYOjnOkLCcuVSAo0UM',
    'COMP_346_UGRD': 'https://chat.whatsapp.com/D1oWcMZMyZa9aqOHh4SOlY',
    'COMP_345_UGRD': 'https://chat.whatsapp.com/Dk2npwYGUCW4gNTE9l1KFz',
    'COMP_218_UGRD': 'https://chat.whatsapp.com/DuIHYZEthDC5Rers6IwP6v',
    'COMP_354_UGRD': 'https://chat.whatsapp.com/BXtwcoQE0C04lqYSbNyq61',
    'COMP_353_UGRD': 'https://chat.whatsapp.com/BoATtwpt5SxID3hrszu4nf',
    'COMP_371_UGRD': 'https://chat.whatsapp.com/FX2eyEBcr14E1EkZyPHFmv',
    'COMP_326_UGRD': 'https://chat.whatsapp.com/HTqCdLDSz2LLYVLiDFFMuj',
    'SOEN_228_UGRD': 'https://chat.whatsapp.com/ELJUvJReEugAkwyfgWQj4M',
    'SOEN_287_UGRD': 'https://chat.whatsapp.com/Fd0AV0TJEKR4sj2kW6qJlZ',
    'SOEN_331_UGRD': 'https://chat.whatsapp.com/L881EL8NKYVKPL6UmpUOeN',
    'SOEN_341_UGRD': 'https://chat.whatsapp.com/CrDJSjZ4nLV1U0kscPTuhK',
    'SOEN_363_UGRD': 'https://chat.whatsapp.com/DtXBe2ez06366wVlPUPXhP',
    'SOEN_343_UGRD': 'https://chat.whatsapp.com/GeDkxmiYOie3c0Qpksa1QB',
    'SOEN_390_UGRD': 'https://chat.whatsapp.com/BEH8D7TVtCP8LlIx1p8ZLp',
    'SOEN_385_UGRD': 'https://chat.whatsapp.com/H7UODQgf3CyL7jI1dcIrnE',
    'SOEN_357_UGRD': 'https://chat.whatsapp.com/LOBw43uDBcb7FM58TFIxxN',
    'SOEN_345_UGRD': 'https://chat.whatsapp.com/KYGj4J9O1W88QUWfCafYwM',
    'SOEN_384_UGRD': 'https://chat.whatsapp.com/GeoKprZrLBK4592YzG1s75',
    'SOEN_342_UGRD': 'https://chat.whatsapp.com/Fr3KnnoDjIOGRXc4fOeuEh',
    'SOEN_321_UGRD': 'https://chat.whatsapp.com/BDw3neNO38h6lGbknCuxt4',
    'PHYS_204_UGRD': 'https://chat.whatsapp.com/IoWzJVtaPLuHyCz1w3gvkX',
    'PHYS_205_UGRD': 'https://chat.whatsapp.com/C06YpnxBken6H0vge2Ue79',
    'ELEC_273_UGRD': 'https://chat.whatsapp.com/EmfgxCH3Vyq0DaaHhbBSFs',
    'ELEC_275_UGRD': 'https://chat.whatsapp.com/LBfJpqnsDwhCwBoo6jiUXU',
    'COEN_243_UGRD': 'https://chat.whatsapp.com/JMEzSHyONLq1dMJoeuG40G',
    'COEN_212_UGRD': 'https://chat.whatsapp.com/B5DvUPdbVNdAtd2H3LzTWE',
    'MAST_218_UGRD': 'https://chat.whatsapp.com/IWfMdrq005P7qrJwMxWDAD',
    'ENCS_282_UGRD': 'https://chat.whatsapp.com/EaGUCwNpHjS7uqTBThVevo',
    'MIAE_211_UGRD': 'https://chat.whatsapp.com/GasOIBM1iju4bkXPt4cTSX',
    'MIAE_311_UGRD': 'https://chat.whatsapp.com/BQ9Y3sIN1XoJ8kGlFM3q6d',
    'MIAE_312_UGRD': 'https://chat.whatsapp.com/C4OXWfw0Brb1J8IlJzwsdp',
    'MIAE_380_UGRD': 'https://chat.whatsapp.com/DuYGwlYuUopK85U20Jdke8',
    'AERO_201_UGRD': 'https://chat.whatsapp.com/Fxs7A0l5MNLIj3v15GbMQI',
    'AERO_290_UGRD': 'https://chat.whatsapp.com/JURX9P4FygvG20D9rDjXv6',
    'AERO_371_UGRD': 'https://chat.whatsapp.com/BC1deQv784a3wH9G1lbbqL',
    'AERO_390_UGRD': 'https://chat.whatsapp.com/BBZntfhSBTKDTNAKMUpsic',
    'AERO_417_UGRD': 'https://chat.whatsapp.com/EmJ2QDncLeTFRNtUU03wmH',
    'AERO_481_UGRD': 'https://chat.whatsapp.com/LxEo8LEAAYD1YqaaBmlHSQ',
    'AERO_455_UGRD': 'https://chat.whatsapp.com/Cb75ctxngWzELSscCczAav',
    'AERO_464_UGRD': 'https://chat.whatsapp.com/KhF1kL0y4NNJ30iW06wmq8',
    'MECH_343_UGRD': 'https://chat.whatsapp.com/H6CXm5F6xcD0QJnsks09OS',
    'MECH_351_UGRD': 'https://chat.whatsapp.com/EoYa5CJVlkEGhAXfmIC0W7',
    'MECH_361_UGRD': 'https://chat.whatsapp.com/FGKEuFytDuw7bE0noSzxx7',
    'MECH_352_UGRD': 'https://chat.whatsapp.com/FYQvI05w3sQ2HuovMrMg3q',
    'MECH_373_UGRD': 'https://chat.whatsapp.com/J5WCIvoG8njKBZoY00xNhk',
    'MECH_375_UGRD': 'https://chat.whatsapp.com/FFIAs4WS4py30v4u6bYIzb',
    'MECH_370_UGRD': 'https://chat.whatsapp.com/JHE0wAkWulVK4M5tSrPi29',
    'MECH_380_UGRD': 'https://chat.whatsapp.com/EtO0NUs1q2oCzH9XyRWy80',
    'MECH_371_UGRD': 'https://chat.whatsapp.com/H2z5wNXUc1U3gqLe6aClFM',
    'MECH_368_UGRD': 'https://chat.whatsapp.com/IDo6FEgLNmO9oazq24s2YW',
    'MECH_321_UGRD': 'https://chat.whatsapp.com/LQIIndMJJ0739FOrG9i7IG',
    'MECH_344_UGRD': 'https://chat.whatsapp.com/B6tm2jDl4It3AEOLZ60ftY',
    'MECH_390_UGRD': 'https://chat.whatsapp.com/F7JcxL0GwmcCiwWweYsB5v',
    'INDU_323_UGRD': 'https://chat.whatsapp.com/Bi9zN5sxbtuAUiu7aBOFhI',
    'INDU_371_UGRD': 'https://chat.whatsapp.com/DMCOPLMaxbF00y8jlVgWHl',
    'INDU_311_UGRD': 'https://chat.whatsapp.com/L0skWxKI2vgAV93Q8jlazd',
    'INDU_320_UGRD': 'https://chat.whatsapp.com/Lkh89s0ZvbC6YageLBvmWw',
    'INDU_324_UGRD': 'https://chat.whatsapp.com/Dpt82pYrXLQG3dNEr7rn2J',
    'INDU_330_UGRD': 'https://chat.whatsapp.com/CIGZg73DO4N5h9gKy5z71l',
    'INDU_321_UGRD': 'https://chat.whatsapp.com/HCdCumu2QaDDNmXqOM9TWX',
    'INDU_342_UGRD': 'https://chat.whatsapp.com/CT4hpk1iBFLJEjPa0bwvTp',
    'INDU_372_UGRD': 'https://chat.whatsapp.com/ENOgjspdLwe0HfPsqfZM6Z',
    'INDU_411_UGRD': 'https://chat.whatsapp.com/LlVuRH42Q3O16yqScAjWsg',
};

export const subjectBaseUrls: { [key: string]: string } = {
    'ECON': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-31-faculty-of-arts-and-science/section-31-080-department-of-economics/economics-courses.html',
    'BIOL': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-31-faculty-of-arts-and-science/section-31-030-department-of-biology/biology-courses.html',
    'PHYS': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-31-faculty-of-arts-and-science/section-31-230-department-of-physics/physics-courses.html',
    'MATH': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-31-faculty-of-arts-and-science/section-31-200-department-of-mathematics-and-statistics/mathematics-and-statistics-courses.html',
    'MAST': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-31-faculty-of-arts-and-science/section-31-200-department-of-mathematics-and-statistics/mathematics-and-statistics-courses.html',
    'MIAE': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-71-gina-cody-school-of-engineering-and-computer-science/section-71-60-engineering-course-descriptions.html',
    'ENGR': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-71-gina-cody-school-of-engineering-and-computer-science/section-71-60-engineering-course-descriptions.html',
    'AERO': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-71-gina-cody-school-of-engineering-and-computer-science/section-71-60-engineering-course-descriptions.html',
    'ENCS': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-71-gina-cody-school-of-engineering-and-computer-science/section-71-60-engineering-course-descriptions.html',
    'MECH': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-71-gina-cody-school-of-engineering-and-computer-science/section-71-60-engineering-course-descriptions.html',
    'INDU': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-71-gina-cody-school-of-engineering-and-computer-science/section-71-60-engineering-course-descriptions.html',
    'CHEM': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-31-faculty-of-arts-and-science/section-31-050-department-of-chemistry-and-biochemistry/chemistry-and-biochemistry-courses.html',
    'COMP': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-71-gina-cody-school-of-engineering-and-computer-science/section-71-70-department-of-computer-science-and-software-engineering/section-71-70-10-computer-science-and-software-engineering-courses.html',
    'SOEN': 'https://www.concordia.ca/academics/undergraduate/calendar/current/section-71-gina-cody-school-of-engineering-and-computer-science/section-71-70-department-of-computer-science-and-software-engineering/section-71-70-10-computer-science-and-software-engineering-courses.html',
};

export const config = {
    name: "Study groups @Concordia",
    url: "https://concordia-groups.web.app",
    ogImage: "/og.png",
    description:
        "Join your course's study group chat on WhatsApp or Discord",
    links: {
        twitter: "",
        github: ""
    },
    keywords: `Concordia University,Study groups,help,courses,Course Chat,WhatsApp Course Groups,Study Chat,Discord Study Groups`
};

export let isLinkPopUpModelOpen = writable(false);
export let linkPopUpModelData = writable({courseName: "", courseWhatsappURL: ""})